tasks:
  - name: Worker
    init: |
      go install honnef.co/go/tools/cmd/staticcheck@latest  # install staticcheck  - fix for 'Analysis Tools Missing' warning in status bar
      go get -v -t -d ./...  # Go Get Fetcher  - see https://www.gitpod.io/docs/languages/go/#start-up-tasks
      pushd temporal-server
      docker-compose pull
      popd
    command: |
      cp .bash_aliases ~/.bash_aliases   # ensure new terminals also have access to tctl
      gp sync-done dockerpull
      echo "waiting for server...."
      gp ports await 7233 && gp ports await 8080 && sleep 25 && gp preview $(gp url 8080)
      clear
      echo "Use this terminal to start your worker."
      source ~/.bash_aliases
  - name: Terminal
    command: |
      gp open README.md
      clear
      echo "Use this terminal to run commands.."
      source ~/.bash_aliases
    openMode: split-right
  - name: Temporal Local Development Server
    command: |
      gp sync-await dockerpull #wait for docker server to be up
      source ~/.bash_aliases
      cd temporal-server
      docker-compose up
    openMode: tab-after

ports:
  - name: Postgres (for Temporal Cluster)
    port: 5432
    onOpen: ignore
  - name: Temporal Server
    port: 7233
    onOpen: ignore
  - name: Temporal Web UI v2
    port: 8080 # temporal UI
    description: New (v2) Temporal Web UI
    onOpen: ignore
    visibility: private
  - name: Temporal Web UI v1
    description: Old (v1) Temporal Web UI
    port: 8088 # temporal legacy UI
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - golang.Go
    - ms-python.python
    - redhat.java
    - vscjava.vscode-java-test
    - vscjava.vscode-java-debug
    - wingrunr21.vscode-ruby
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
