# this is a config file for gitpod setup, ignore if you are running samples locally
# See readme at https://github.com/temporalio/samples-typescript/blob/main/.gitpod.readme.md

tasks:
  - name: Worker
    init: |
      alias tctl="docker exec temporal-admin-tools tctl"
      cd temporal-server
      docker-compose pull
      cd
    command: |
      gp sync-done dockerpull
      gp await-port 7233
      gp preview $(gp url 8080)
      clear
      echo "tctl configured! try typing tctl -v"
      echo "Use this terminal to start your worker."
  - name: Terminal
    init: |
      alias tctl="docker exec temporal-admin-tools tctl"
    command: |
      gp open README.md
      clear
      echo "tctl configured! try typing tctl -v"
      echo "Use this terminal to run commands"
    openMode: split-right
  - name: Temporal Server
    command: |
      gp sync-await dockerpull
      cd temporal-server
      docker-compose up
    openMode: split-right

ports:
  - port: 5432 # postgres
    onOpen: ignore
  - port: 7233 # temporal server
    onOpen: ignore
  - port: 8080 # temporal UI
    onOpen: ignore
    visibility: public
  - port: 8088 # temporal legacy UI
    onOpen: ignore
    visibility: public
