# this is a config file for gitpod setup, ignore if you are running samples locally
# See readme at https://github.com/temporalio/samples-typescript/blob/main/.gitpod.readme.md

tasks:
  - name: Worker
    init: |
      alias tctl="docker exec temporal-admin-tools tctl"
      echo "tctl configured! try typing tctl -v"
      docker-compose pull
      gp sync-done dockerpull
    command: |
      gp sync-await dockerpull
      gp sync-await server
      gp await-port 7233 && go run worker/main.go
  - name: Terminal
    init: |
      alias tctl="docker exec temporal-admin-tools tctl"
      echo "tctl configured! try typing tctl -v"
    command: |
      gp open README.md
      # gp await-port 8088 && gp preview http://localhost:8088 # open up Temporal Web to show new workflow
    openMode: split-right
  - name: Temporal Server
    command: |
      gp sync-await dockerpull
      docker-compose up -d
    openMode: split-right

ports:
  - port: 5432 # postgres
    onOpen: ignore
  - port: 7233 # temporal server
    onOpen: ignore
  - port: 8088 # temporal web
    onOpen: open-preview
    visibility: public
