image: gitpod/workspace-full:2023-01-16-03-31-28
tasks:
  - name: Worker
    init: |
      cp .bash_aliases ~/.bash_aliases   # ensure new terminals also have access to tctl
      # install staticcheck
      go install honnef.co/go/tools/cmd/staticcheck@latest  # fix for 'Analysis Tools Missing' warning in status bar
      # install temporal cli
      curl -sSf https://temporal.download/cli.sh | sh
      gp sync-done temporal-cli
      # install tctl for backwards compat
      curl -sL -O https://github.com/temporalio/tctl/releases/download/v1.18.0/tctl_1.18.0_linux_amd64.tar.gz
      tar zxvf tctl_1.18*
      mv tctl /home/gitpod/.temporalio/bin/tctl
      chmod +x /home/gitpod/.temporalio/bin/tctl
    command: |
      echo "waiting for server...."
      gp ports await 7233 && gp ports await 8080 && sleep 25 && gp preview $(gp url 8080)
      clear
      source .bash_aliases
      echo "Use this terminal to start your worker."
    openMode: split-right
  - name: Terminal
    command: |
      gp open README.md
      clear
      echo "Use this terminal to run commands.."
      source .bash_aliases
    openMode: split-right
  - name: Temporal Local Development Server
    command: |
      source .bash_aliases
      gp sync-await temporal-cli
      temporal server start-dev --db-filename your_temporal.db --ui-port 8080
    openMode: tab-after

ports:
  - name: Temporal server
    port: 7233
    onOpen: ignore
  - name: Temporal Web UI
    port: 8080 # temporal UI
    description: Temporal Web UI
    onOpen: ignore
    visibility: private
  - name: Greeting Service
    description: Local microservice used in exercises
    port: 9999
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - golang.Go
    - ms-python.python
    - redhat.java
    - vscjava.vscode-java-test
    - vscjava.vscode-java-debug
    - wingrunr21.vscode-ruby
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow
