# this is a config file for gitpod setup, ignore if you are running samples locally
# See readme at https://github.com/temporalio/samples-typescript/blob/main/.gitpod.readme.md

workspaceLocation: "~"
tasks:
  - name: Worker
    init: |
      cd temporal-server
      docker-compose pull
    command: |
      gp sync-done dockerpull
      clear
  - name: Terminal
    init: |
      alias tctl="docker exec temporal-admin-tools tctl"
    command: |
      gp open README.md
      clear
      echo "tctl configured! try typing tctl -v"
      echo "Use this terminal to run commands"
    openMode: split-right
  - name: Temporal Server
    command: |
      gp sync-await dockerpull
      cd temporal-server
      docker-compose up
    openMode: tab-after

ports:
  - name: postgres
    port: 5432
    onOpen: ignore
  - name: Temporal server
    port: 7233
    onOpen: ignore
  - name: Temporal Web UI
    port: 8080 # temporal UI
    onOpen: open-preview
    visibility: private

vscode:
  extensions:
    - golang.Go
    - ms-python.python
    - redhat.java
    - vscjava.vscode-java-test
    - vscjava.vscode-java-debug
    - wingrunr21.vscode-ruby
