# this is a config file for gitpod setup, ignore if you are running samples locally
# See readme at https://github.com/temporalio/samples-typescript/blob/main/.gitpod.readme.md

tasks:
  - name: Worker
    init: |
      cp .bash_aliases ~/.bash_aliases   # ensure new terminals also have access to tctl
      pushd temporal-server
      docker-compose pull
      popd
    command: |
      gp sync-done dockerpull
      echo "waiting for server...."
      gp ports await 7233 && gp ports await 8080 && sleep 20 && gp preview http://localhost:8080
      clear
      echo "Use this terminal to start your worker."
      source ~/.bash_aliases
  - name: Terminal
    command: |
      gp open README.md
      clear
      echo "Use this terminal to run commands.."
      source ~/.bash_aliases
    openMode: split-right
  - name: Temporal Local Development Server
    command: |
      gp sync-await dockerpull
      cd temporal-server
      docker-compose up
    openMode: tab-after

ports:
  - name: postgres
    port: 5432
    onOpen: ignore
  - name: Temporal server
    port: 7233
    onOpen: ignore
  - name: Temporal Web UI
    port: 8080 # temporal UI
    onOpen: ignore
    visibility: private
  - name: Temporal Web UI
    port: 8088 # temporal legacy UI
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - golang.Go
    - ms-python.python
    - redhat.java
    - vscjava.vscode-java-test
    - vscjava.vscode-java-debug
    - wingrunr21.vscode-ruby
